import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import Navbar from "@/components/Navbar";
import { Prompt } from "next/font/google";

const prompt = Prompt({subsets: ["latin", "thai"], weight: ["400", "700"]});

export const metadata: Metadata = {
  title: "Tic Tac Toe With Ai",
  description: "Generated by Anuwat Chaoyai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${prompt.className} dark bg-background`}
      >
        <UserProvider>
        <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
